# Custom environment variables override all configuration files,
# including local.json. Only command line options take precedence over them.

api:
  server:
    port: PORT
  logger:
    transports:
      File:
        options:
          label: NODE_APP_INSTANCE