logger: &logger
  path: ./
  transports: &logger-transports
    File:
      type: File
      options: &logger-file-options
        filename: default.log
        level: info
        json: false
        maxsize: 5242880
        maxFiles: 100
        timestamp: true
        prettyPrint: true
        colorize: true
        tailable: true
    Console:
      type: Console
      options: &logger-console-options
        level: info
        json: false
        timestamp: true
        prettyPrint: true
        colorize: true
  middleware:
    requestWhitelist:
#      - body
#      - headers
#      - method
      - ip
#      - ips
#      - query
#      - params
#      - path
#      - url
#      - baseUrl
#      - originalUrl
#      - fresh
#      - xhr
#      - subdomains
#      - protocol
    responseWhitelist:
      - statusCode
      - locals
#      - body

#   Template Loggly transport configuration
#
#   NOTE: Add token and subdomain to your local configuration file
#
#   - type: Loggly
#     options:
#       level: info
#       subdomain: The subdomain of your Loggly account [required]
#       inputToken: The input token [required]
#       tags:
#         - your tags here
#         - another tag
#       json: true
#       stripColors: true
  levels:
    debug: 4
    verbose: 3
    info: 2
    warn: 1
    error: 0
  colors:
    debug: blue
    verbose: white
    info: green
    warn: yellow
    error: red

swagger: &swagger
  validator:
    validateResponse: false
  ui: &swagger-ui
    swaggerUi: /docs
    apiDocs: /api-docs
  swaggerDefinition: &swaggerDefinition
    host: localhost:8000 # Host (optional)
    schemes:
      - http
    consumes:
      - application/json
    produces:
      - application/json
  oauth2:
    authorizationUrl: http://localhost:8000/oauth2/login

version: 0

oauth2:
  mountPath: /oauth2
  authorizationUrl: http://localhost:8000/oauth2/login
  routes:
    - ./src/oauth2
  logger:
    middleware:
      requestWhitelist:
        - ip
      responseWhitelist:
        - statusCode

caller:
  connection:
    url: amqp://localhost
  queue:
    name: 'rpc_dev'

api: &api
  # use mountPath to version your endpoints /<version>
  mountPath: '/0'
  logger:
    <<: *logger
    middleware:
      requestWhitelist:
        - ip
      responseWhitelist:
        - statusCode
    transports:
      <<: *logger-transports
      File:
        type: File
        options:
          <<: *logger-file-options
          filename: api.log
  routesDirs:
    - './src/api/routes'
  swagger:
    <<: *swagger
    outputSpec: ./api-docs.json
    swagger-ui:
      <<: *swagger-ui
    swaggerDefinition:
      <<: *swaggerDefinition
      info: # API informations (required)
        version: '0.1.0' # Version (required)
        title: API-NODE-SWAGGER # Title (required)
        description: Example API layer # Description (optional)
      basePath: /0 # basePath (optional)
    docsDirs:
      - ./src/api
      - ./src/api/definitions
      - ./src/api/routes

superadmin:
  <<: *api
  logger:
    middleware:
      requestWhitelist:
        - ip
      responseWhitelist:
        - statusCode
  routes:
    - ./src/api/routes/swagger
  swagger:
    <<: *swagger
    outputSpec: ./sa-api-docs.json
    ui:
      swaggerUi: /superadmin-docs
      apiDocs: /superadmin-api-docs
    swaggerDefinition:
      <<: *swaggerDefinition
      basePath: /0 # basePath (optional)
      info:
        # API information (required)
        version: '0.1.0' # Version (required)
        title: API-NODE-SWAGGER Superadmin # Title (required)
        description: Example Superadmin API layer # Description (optional)
    docsDirs:
      - ./src/api
      - ./src/api/definitions
      - ./src/api/routes/superadmin

server:
  port: 8000
  strictToken: false
  views:
    path: './src/views'
    extname: '.hbs'
    defaultLayout: 'main'
    layoutsDir: './src/views/layouts'
    partialsDir:
      dir: './src/views/partials'
      namespace: 'partials'
  cors:
    origin: true
    maxAge: 172800
    preflightContinue: true
    allowedHeaders:
      - Accept
      - Content-Type
      - Authorization
    methods:
      - GET
      - HEAD
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
