oauth2:
  logger:
    middleware: false

caller:
  queue:
    name: rpc

api:
  logger:
    middleware: false
    transports:
      Console: false
  swagger:
    ui: false
    serveDocs: /api-docs

superadmin:
  logger:
    middleware: false
  swagger:
    ui: false
    serveDocs: false
