server:
  port: 8080

api:
  logger: false
  swagger:
    ui: false
    serveDocs: false
    validator:
      validateResponse: true

superadmin:
  logger: false
  swagger:
    ui: false
    serveDocs: false
    validator:
      validateResponse: true

caller:
  queue:
    name: rpc_test
